### ISSUE TITLE
A word about Raspberries

### ISSUE THREAD

**Issue by nerdaxic** [R2D2FISH/glados-tts#1]
Thank you so much for sharing your model!

I'm trying to integrate the model to my [GLaDOS Voice Assistant](https://github.com/Nerdaxic/GLaDOS-Voice-Assistant) project. Tried running it on Raspberry Pi 4 V1.4 for shits and giggles, turns out that script won't run, because the CPU is missing support for avx2 instruction set.

`RuntimeError: Unknown qengine`

**Suggestion:** Add a comment to README.md file to save other's time:
_Torch requires GPU or avx2 capable CPU to run the model, it will not run on Raspberry Pi._

**Comment by R2D2FISH** [comment]
If you convert the model to onnx and then to ncnn, you could probably run the model under vulkan on the Pi...
