### ISSUE TITLE
No longer can access the model files due to git lfs quota

### ISSUE THREAD

**Issue by nalf3in** [R2D2FISH/glados-tts#13]
I just realised this repo now uses github lfs for the model files. Unfortunately trying to pull the files gives this error:

```
git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                                      
error: failed to fetch some objects from 'https://github.com/R2D2FISH/glados-tts.git/info/lfs'
```

Here's a workaround https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh but the models will probably need to be hosted elsewhere or be included with "classic" git if possible. 

I can look for a file host for the models or host them on my server via torrent if desired

**Comment by R2D2FISH** [comment]
I can host them on Google Drive maybe? I didn't want to use LFS but the new model file is too big to upload normally.
Edit: added Google Drive link

**Comment by nalf3in** [comment]
Apparently google drive has no download limit so that's perfect. Thank you for the quick response : )
